### ISSUE TITLE
Implement layout for SMWT

### ISSUE THREAD

**Issue by femosc2** [Mobistudy/Mobistudyapp#41]

**Comment by dariosalvi78** [comment]
you can reuse the "task" layout or implement a new one.

With the generic layout you need to find a way to know when the user has pressed the cancel button so that you can stop all sensors and GPS. You can obtain this by launching an event and having your component registered to it, see [this](https://stackoverflow.com/questions/48818110/access-refs-from-other-components-not-in-the-same-level-as-current-component).

If you use a custom layout, you can include that logic into the layout.
